version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    ui-default:
        image: ziwei000/opendlv-ui-default:v0.0.2
        network_mode: "host"
        #volumes:
        #  - ./simulation-map.txt:/srv/http/simulation-map.txt
        command: "--cid=${CID}"

    odcockpit:
        image: seresearch/opendlv-cfsd18-on-opendlv-lynx-on-opendlv-on-opendlv-core-on-opendavinci-on-base-dev:latest
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        #- .:/opt/opendlv.data
        - ~/opendlv/opendlv.cfsd18/code/logic-cfsd18/perception/detectconelane/src:/opt/testdata
        - ~/Downloads/LidarRecordings:/opt/Recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"  