version: '2'

services:
    sim-global:
        image: chalmersrevere/opendlv-sim-global-amd64:v0.0.5
        network_mode: "host"
        command: "/usr/bin/opendlv-sim-global --cid=111 --freq=10 --frame-id=0 --x=0 --y=1.5 --yaw=-2.356"

    ui-default:
        image: opendlv-ui-default:v0.0.1
        network_mode: "host"
        volumes:
          - ./simulation-map-closed-lap.txt:/srv/http/simulation-map-closed-lap.txt
        command: "--cid=111"
